# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
port:             4000
url:              http://grvpanchal.github.io/bootstrap-essentials
baseurl:          "/bootstrap-essentials"
encoding:         UTF-8

gems:
  - jekyll-sitemap

# Custom vars
current_version:  0.3
repo:             https://github.com/grvpanchal/bootstrap-essentials

download:
  source:         https://github.com/grvpanchal/bootstrap-essentials/archive/v0.0.3.zip
  dist:           https://github.com/grvpanchal/bootstrap-essentials/releases/download/v0.0.3/bootstrap-0.0.3-dist.zip
