# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

title: Bootstrap Essentials
description: Essential and common classes for bootstrap for faster web development

# Server
url:              http://bootstrapessentials.com

author:
  twitter: grvpanchal

encoding:         UTF-8

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
bootstrap_version: 3.3.7
current_version:  0.6.0
repository:       https://github.com/grvpanchal/bootstrap-essentials

download:
  source:         https://github.com/grvpanchal/bootstrap-essentials/archive/v0.6.0.zip
  dist:           https://github.com/grvpanchal/bootstrap-essentials/releases/download/v0.6.0/bootstrap-essentials-0.6.0-dist.zip
  bootstrap:       https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip

exclude: 
  - .gitignore
  - README.md
